# Generated by Django 4.2.3 on 2023-08-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_softdesk", "0004_alter_contributor_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "uid",
                    models.CharField(
                        default="7d44e099-c870-4777-9143-3272f3dfda39", max_length=100
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_softdesk.issue",
                    ),
                ),
            ],
        ),
    ]
