# Generated by Django 4.2.3 on 2023-09-18 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_softdesk", "0007_alter_comment_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 9, 18, 14, 42, 26, 225650, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contributor",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 9, 18, 14, 42, 48, 680119, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 9, 18, 14, 42, 55, 652713, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 9, 18, 14, 43, 4, 605264, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="uid",
            field=models.CharField(
                default="772e412b-8d2c-48a2-b640-a86e9562c8f0", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("back-end", "back-end"),
                    ("front-end", "front-end"),
                    ("iOS", "iOS"),
                    ("Android", "Android"),
                ],
                max_length=10,
            ),
        ),
    ]
