# Generated by Django 4.2.3 on 2023-08-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=15),
        ),
    ]
